### ISSUE TITLE
Bouton supprimer note

### ISSUE THREAD

**Issue by shARPII** [Coasters-World/captain-coaster#46]
En dessous des étoiles sur la page de coaster, il faudrait rajouter une icone poubelle qui permettrait de reset/supprimer la note s'il y en a une

**Prio1**

**Comment by J-On-Prod** [comment]
Si vous voulez, je peux faire cette tache ^^

**Comment by richardcrete** [comment]
Done par @florian987 en août dernier, je close le ticket.
