### ISSUE TITLE
Passage de la carte sur open source

### ISSUE THREAD

**Issue by shARPII** [Coasters-World/captain-coaster#49]
Il faudrait passer le système de carte actuellement sur google vers un autre projet style open street maps.
Actuellement, cela nous bride beaucoup dans l'utilisation, avec un autre projet, on pourrait beaucoup plus utiliser la map et l'afficher un peu partout.

Avec google maps, on est limité par le nombre d'utilisation par jour autorisé.

**Prio1**

**Comment by shARPII** [comment]
PR sur #56 
Utilisation de https://github.com/CartoDB/basemap-styles plutôt que Open Street Map.
Dans la doc, si c'est une utilisation non commerciale, on peut monter à 75k vues par mois.
@florian987 tu me diras si ça te va sinon je peux switch sur OSM mais la carte est pas super sexy.

**Comment by richardcrete** [comment]
La carte OS est bien en place sur la carte générale mais c'est encore Google Maps sur les carte de chaque utilisateur.

Perso j'ai quelques ralentissements aussi.
