### ISSUE TITLE
Update page admin

### ISSUE THREAD

**Issue by shARPII** [Coasters-World/captain-coaster#50]
Plusieurs modifications à voir : 

- Pouvoir supprimer ou plutôt masquer un coaster pour qu'il ne soit plus présent sur le site
- Pouvoir repasser un constructeur d'un coaster en None quand un constructeur est déjà sélectionné
- ...

**Prio1**
Bug

**Comment by shARPII** [comment]
@florian987 comme tu as fait des trucs dessus, est-ce que tout a été traité et on clos l'issue ou tu as encore des trucs à faire dessus?

**Comment by florian987** [comment]
fixed bu ecc2ba8
