### ISSUE TITLE
Réparer miniature top & ranking qui n'apparait pas

### ISSUE THREAD

**Issue by shARPII** [Coasters-World/captain-coaster#57]
Exemple sur T2Z, ça n'a pas l'air de générer l'image carrée ou alors il n'y a pas de mise à jour de la base pour savoir quelle image utiliser.
A investiguer.

**Comment by florian987** [comment]
Fixed by https://github.com/Coasters-World/captain-coaster/commit/569ad3c130ff1f7940b25ed38b88568284a54a21
+ added error logs in case it breaks again in the future
